baseurl = "https://kel.bz/"
languageCode = "en-us"
title = "kel.bz"
theme = "angels-ladder"

[Params]
twitter = "https://twitter.com/kelbyludwig"
github = "https://github.com/kelbyludwig"
showsRSS = true
profile = "https://kel.bz/profile.jpg"
copyright = "Written by Kelby Ludwig"
