baseurl = "https://kel.bz/"
languageCode = "en-us"
title = "kel.bz"
theme = "hugo-notepadium"

[params]
slogan = "Where I take notes."

[params.nav]
# Add a top-level /tags/ page
showTags = true       

[[params.nav.custom]]
# Add a top-level /about/ page
title = "About"
url = "/about/me"

[[params.nav.custom]]
# Add a top-level link to Github
title = "Github"
url = "https://github.com/kelbyludwig"

[[params.nav.custom]]
# Add a top-level link to Twitter
title = "Twitter"
url = "https://twitter.com/kelbyludwig"
