[build]
publish = "public"
command = "hugo --gc -b https://kel.bz -t hugo-notepadium"

[context.deploy-preview]
command = "hugo --gc -b https://kel.bz -t hugo-notepadium"

[context.production.environment]
HUGO_VERSION = "0.62.0"

[context.deploy-preview.environment]
HUGO_VERSION = "0.62.0"
